---
# tasks/main.yml file for role gitolite
- name: Check assertions
  ansible.builtin.assert:
    that:
      - true
    fail_msg: "Assertion failed."
    success_msg: "Assertion succeeded."
    quiet: true
