---
# tasks/main.yml file for role gitolite

- name: Warning if not running on tested Linux family
  ansible.builtin.debug:
    msg: "Warning: This has not been tested on {{ ansible_facts['os_family'] }} based systems"
  when: ansible_facts['os_family'] not in ['Debian', 'RedHat', 'Alpine']

- name: Ensure gitolite user group exists, optionally with custom gid
  ansible.builtin.group:
    name: "{{ gitolite_group }}"
    gid: "{{ gitolite_group_id | default(omit) }}"
    state: present
  notify: Fix User and Group IDs

- name: Ensure gitolite user exists, optionally with custom uid
  ansible.builtin.user:
    name: "{{ gitolite_user }}"
    group: "{{ gitolite_group }}"
    comment: "Gitolite User"
    uid: "{{ gitolite_user_id | default(omit) }}"
    create_home: yes
    state: present
  notify: Fix User and Group IDs

- name: Install RedHat/Debian gitolite Packages
  ansible.builtin.package:
    name:
      - git
      - gitolite3
      - hostname
      - fcgiwrap
    state: present
    update_cache: true
  no_log: true
  when: ansible_facts['os_family'] in ['Debian', 'RedHat']

- name: Install Alpine gitolite Packages
  ansible.builtin.package:
    name:
      - git
      - gitolite
      - openssh-keygen
      - fcgiwrap
    state: present
    update_cache: true
  no_log: true
  when: ansible_facts['os_family'] == "Alpine"

- name: Create or Update Admin User Key
  ansible.builtin.copy:
    content: "{{ gitolite_admin_key }}"
    dest: /home/{{ gitolite_user }}/{{ gitolite_admin_user }}.pub
    owner: "{{ gitolite_user }}"
    mode: '0644'
  notify: Run gitolite Setup

# The remainder of this role deals with getting the fastcgi socket permissions right.

- name: Check if httpd user exists using getent
  ansible.builtin.getent:
    database: passwd
    key: "{{ gitolite_httpd_user }}"
    fail_key: false

- name: Nn more to do if httpd user does not exist
  ansible.builtin.meta: end_role
  when: ansible_facts['getent_passwd'][gitolite_httpd_user] is none

- name: Add httpd to a gitolite group
  ansible.builtin.user:
    name: "{{ gitolite_httpd_user }}"
    groups: "{{ gitolite_group }}"
    append: true

- name: Enable SELinux policy to allow httpd user to access the gitolite socket
  ansible.builtin.include_role:
    name: selinux_policy
  vars:
    selinux_policy_file: "../gitolite/files/httpd-fcgiwrap.te"
    selinux_policy_name: "httpd-fcgiwrap"

- name: Enable and start Fast CGI socket
  ansible.builtin.service:
    name: "fcgiwrap@{{ gitolite_user }}.socket"
    enabled: true
    state: started
  when: ansible_facts['os_family'] not in ['Alpine']
  no_log: true
