---
# tasks/main.yml file for role selinux_tpm2setup

- name: Gather service facts
  ansible.builtin.service_facts:
  no_log: true

- name: Display systemd-tpm2-setup service status
  ansible.builtin.debug:
    var: ansible_facts.services['systemd-tpm2-setup.service']

- name: End role if systemd-tpm2-setup did not fail
  ansible.builtin.meta: end_role
  when: ansible_facts.services['systemd-tpm2-setup.service'].status != 'failed'

- name: Fetch logs for systemd-tpm2-setup service
  ansible.builtin.command: journalctl -u systemd-tpm2-setup --no-pager
  register: tpm2setup_output
  changed_when: false
  no_log: true

- name: Display the systemd-tpm2-setup log entries
  ansible.builtin.debug:
    msg: "{{ tpm2setup_output.stdout_lines }}"

- name: End role if systemd-tpm2-setup did not fail on permission denied
  ansible.builtin.meta: end_role
  when: tpm2setup_output.stdout_lines | map('regex_search', 'Failed to write anchor secret file to .* Permission denied') | select | list | length < 1

- name: Apply SELinux policy to fix systemd-tpm2-setup.service
  ansible.builtin.include_role:
    name: selinux_policy
  vars:
    selinux_policy_file: "../selinux_tpm2setup/files/systemd-tpm2-setup.te"
    selinux_policy_name: "systemd-tpm2-setup"

- name: Restart the service
  ansible.builtin.service:
    name: systemd-tpm2-setup
    state: started
  no_log: true
